In [1]:
n = [[12, 3, 5], [], []]
n

[[12, 3, 5], [], []]

In [2]:
type(n)

list

In [3]:
import numpy

In [4]:
a=numpy.arange(27)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [12]:
a.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [1]:
import cv2

In [6]:
img=cv2.imread("smallgray.png")
img

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [3]:
img=cv2.imread("smallgray.png",0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [4]:
img=cv2.imread("smallgray.png",1)
img

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [7]:
img2=cv2.imread("edit.png")
img2

array([[[106, 103, 102],
        [106, 103, 102],
        [105, 103, 102],
        ...,
        [116, 116, 116],
        [116, 116, 117],
        [116, 116, 117]],

       [[105, 102, 101],
        [105, 102, 101],
        [104, 102, 101],
        ...,
        [115, 116, 116],
        [115, 116, 116],
        [115, 116, 116]],

       [[105, 102, 101],
        [104, 102, 100],
        [104, 102, 100],
        ...,
        [115, 115, 115],
        [115, 115, 115],
        [115, 115, 116]],

       ...,

       [[ 40,  42,  58],
        [ 45,  48,  64],
        [ 47,  51,  66],
        ...,
        [ 41,  47,  64],
        [ 41,  47,  64],
        [ 45,  53,  69]],

       [[ 38,  41,  57],
        [ 43,  46,  63],
        [ 46,  49,  65],
        ...,
        [ 45,  52,  67],
        [ 47,  53,  69],
        [ 46,  55,  71]],

       [[ 39,  43,  59],
        [ 42,  46,  62],
        [ 43,  47,  62],
        ...,
        [ 46,  54,  69],
        [ 48,  56,  70],
        [ 44,  53,  68]]

In [10]:
cv2.imwrite('imagecopy.png',img2)

True

In [12]:
img[0:2]

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]]], dtype=uint8)

In [14]:
img=cv2.imread('smallgray.png',0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
img[0:2,0:3]

array([[187, 158, 104],
       [198, 125, 255]], dtype=uint8)

In [20]:
for i in img:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [21]:
for i in img.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [22]:
for i in img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
